# theme: jekyll-theme-minimal
remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Chris's Blog
description: Stay curious
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
minima:
  skin: classic
  nav_pages:
    - about.md

  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/jekyll/jekyll"
    # - title: Jekyll at X (formerly Twitter)
    #   icon: x-twitter
    #   url: "https://x.com/jekyllrb"
  show_excerpts: true
  date_format: "%b %-d, %Y"
  hide_site_feed_link: true

author:
  name: Chris Zhu
  email: "ChrisZhu@foobar.com"